from key in scan("exo.mesh.*")
select key

from key in scan("exo.mesh.*")
where key.kind == "CrownDesign"
select key

from key in scan("exo.mesh.*")
let meta = key["meta"]
where meta.kind == "LibraryModel"
select meta.filename

from meshKey in scan("exo.mesh.*")
from sessionKey in "exo.session.*"
where meshKey["meta"].sessionKey == sessionKey
select (meshKey, sessionKey)

from key in scan("exo.mesh.*")
from hkey in hkeys(key, "data-*")
where len(key[hkey]) > 0
select (key, hkey)
